version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: hoztech_postgres
    environment:
      POSTGRES_DB: hoztech_db
      POSTGRES_USER: hoztech_user
      POSTGRES_PASSWORD: hoztech_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hoztech_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hoztech_user -d hoztech_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: hoztech_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hoztech_network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:

networks:
  hoztech_network:
    driver: bridge 