# Generated by Django 5.2.1 on 2025-05-22 14:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CookiePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('essential_cookies', models.BooleanField(default=True)),
                ('performance_cookies', models.BooleanField(default=True)),
                ('marketing_cookies', models.BooleanField(default=True)),
                ('first_visit', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_visit', models.DateTimeField(auto_now=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('change_history', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Preferência de Cookie',
                'verbose_name_plural': 'Preferências de Cookies',
                'ordering': ['-last_visit'],
            },
        ),
    ]
