# Generated by Django 5.2.1 on 2025-05-22 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoztech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiepreference',
            name='browser_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='device_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='is_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='is_tablet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='is_touch_capable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='screen_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='screen_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookiepreference',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='cookiepreference',
            index=models.Index(fields=['device_type'], name='hoztech_coo_device__827d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='cookiepreference',
            index=models.Index(fields=['browser'], name='hoztech_coo_browser_31dae2_idx'),
        ),
        migrations.AddIndex(
            model_name='cookiepreference',
            index=models.Index(fields=['os'], name='hoztech_coo_os_0dd141_idx'),
        ),
        migrations.AddIndex(
            model_name='cookiepreference',
            index=models.Index(fields=['last_visit'], name='hoztech_coo_last_vi_5a0b72_idx'),
        ),
        migrations.AddIndex(
            model_name='cookiepreference',
            index=models.Index(fields=['is_mobile', 'is_tablet', 'is_pc'], name='hoztech_coo_is_mobi_f5e64a_idx'),
        ),
    ]
