# Generated by Django 5.2.1 on 2025-05-22 19:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoztech', '0002_cookiepreference_browser_version_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuthImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='admin_auth_images/')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['category'], name='hoztech_adm_categor_e0a2e9_idx'), models.Index(fields=['is_active'], name='hoztech_adm_is_acti_360f16_idx')],
            },
        ),
        migrations.CreateModel(
            name='VisitorAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('isp', models.CharField(blank=True, max_length=255, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['ip_address'], name='hoztech_vis_ip_addr_d364df_idx'), models.Index(fields=['timestamp'], name='hoztech_vis_timesta_2c8bba_idx'), models.Index(fields=['session_id'], name='hoztech_vis_session_69af3d_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='hoztech_adm_user_id_6d58d4_idx'), models.Index(fields=['timestamp'], name='hoztech_adm_timesta_228901_idx'), models.Index(fields=['action'], name='hoztech_adm_action_7dee39_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdminUserAuthPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_2fa_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auth_images', models.ManyToManyField(related_name='selected_by_users', to='hoztech.adminauthimage')),
                ('last_auth_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_used_by', to='hoztech.adminauthimage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['is_2fa_enabled'], name='hoztech_adm_is_2fa__52eae8_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('export_type', models.CharField(choices=[('cookies', 'Cookies'), ('access', 'Acessos'), ('all', 'Todos os Dados')], max_length=50)),
                ('date_range_start', models.DateTimeField()),
                ('date_range_end', models.DateTimeField()),
                ('file_path', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluído'), ('failed', 'Falhou')], default='pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='hoztech_dat_user_id_0eb408_idx'), models.Index(fields=['timestamp'], name='hoztech_dat_timesta_4f1fb5_idx'), models.Index(fields=['export_type'], name='hoztech_dat_export__fc6247_idx')],
            },
        ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cookie_name', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('essential', 'Essencial'), ('performance', 'Desempenho'), ('marketing', 'Marketing'), ('analytics', 'Analytics')], max_length=50)),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookie_consents', to='hoztech.visitoraccess')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['cookie_name'], name='hoztech_coo_cookie__d854f7_idx'), models.Index(fields=['timestamp'], name='hoztech_coo_timesta_bc6cd3_idx'), models.Index(fields=['category'], name='hoztech_coo_categor_72276c_idx')],
            },
        ),
    ]
