# Generated by Django 5.2.1 on 2025-05-22 22:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoztech', '0003_adminauthimage_visitoraccess_adminaccesslog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDownload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Empresa')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Aceito receber comunicações de marketing')),
                ('source', models.CharField(default='website', max_length=50, verbose_name='Origem do lead')),
            ],
            options={
                'verbose_name': 'Download de PDF',
                'verbose_name_plural': 'Downloads de PDF',
                'ordering': ['-created_at'],
            },
        ),
    ]
