# Generated by Django 5.2.1 on 2025-05-22 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoztech', '0004_pdfdownload'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdownload',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Quantidade de vezes que o PDF foi baixado', verbose_name='Número de downloads'),
        ),
        migrations.AddField(
            model_name='pdfdownload',
            name='email_error',
            field=models.TextField(blank=True, help_text='Mensagem de erro caso o envio do e-mail falhe', null=True, verbose_name='Erro no envio do e-mail'),
        ),
        migrations.AddField(
            model_name='pdfdownload',
            name='email_sent',
            field=models.BooleanField(default=False, help_text='Indica se o e-mail com o PDF foi enviado com sucesso', verbose_name='E-mail enviado'),
        ),
        migrations.AddField(
            model_name='pdfdownload',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do envio do e-mail'),
        ),
        migrations.AddField(
            model_name='pdfdownload',
            name='last_download',
            field=models.DateTimeField(blank=True, help_text='Data e hora do último download do PDF', null=True, verbose_name='Último download'),
        ),
        migrations.AddField(
            model_name='pdfdownload',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Arquivo PDF do manual', null=True, upload_to='pdfs/manual_cyberseguranca/', verbose_name='Arquivo PDF'),
        ),
        migrations.AddIndex(
            model_name='pdfdownload',
            index=models.Index(fields=['email'], name='hoztech_pdf_email_1748bf_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdownload',
            index=models.Index(fields=['created_at'], name='hoztech_pdf_created_48f7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdownload',
            index=models.Index(fields=['email_sent'], name='hoztech_pdf_email_s_713d13_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdownload',
            index=models.Index(fields=['marketing_consent'], name='hoztech_pdf_marketi_b9cd7e_idx'),
        ),
    ]
