# Generated by Django 5.2.1 on 2025-05-22 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoztech', '0005_pdfdownload_download_count_pdfdownload_email_error_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pdfdownload',
            name='hoztech_pdf_email_s_713d13_idx',
        ),
        migrations.RemoveField(
            model_name='pdfdownload',
            name='email_error',
        ),
        migrations.RemoveField(
            model_name='pdfdownload',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='pdfdownload',
            name='email_sent_at',
        ),
    ]
