# Generated by Django 5.2.1 on 2025-05-24 23:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoztech', '0007_add_user_to_pdfdownload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookieconsent',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'Consentimento de Cookie', 'verbose_name_plural': 'Consentimentos de Cookies'},
        ),
        migrations.AlterModelOptions(
            name='visitoraccess',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'Acesso de Visitante', 'verbose_name_plural': 'Acessos de Visitantes'},
        ),
        migrations.RemoveIndex(
            model_name='cookieconsent',
            name='hoztech_coo_cookie__d854f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='cookieconsent',
            name='hoztech_coo_timesta_bc6cd3_idx',
        ),
        migrations.RemoveIndex(
            model_name='cookieconsent',
            name='hoztech_coo_categor_72276c_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitoraccess',
            name='hoztech_vis_ip_addr_d364df_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitoraccess',
            name='hoztech_vis_timesta_2c8bba_idx',
        ),
        migrations.RemoveIndex(
            model_name='visitoraccess',
            name='hoztech_vis_session_69af3d_idx',
        ),
        migrations.AddField(
            model_name='adminuserauthpreference',
            name='allowed_ips',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='adminuserauthpreference',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuserauthpreference',
            name='last_login_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuserauthpreference',
            name='last_password_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuserauthpreference',
            name='lock_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminuserauthpreference',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adminuserauthpreference',
            name='notify_on_login',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuserauthpreference',
            name='notify_on_password_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='adminuserauthpreference',
            name='require_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adminuserauthpreference',
            name='session_timeout',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='cookieconsent',
            name='category',
            field=models.CharField(choices=[('essential', 'Essencial'), ('performance', 'Desempenho'), ('marketing', 'Marketing'), ('analytics', 'Analytics')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='cookieconsent',
            name='cookie_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='cookieconsent',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='visitoraccess',
            name='browser',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitoraccess',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitoraccess',
            name='device_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='visitoraccess',
            name='endpoint',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='visitoraccess',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='visitoraccess',
            name='os',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitoraccess',
            name='session_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitoraccess',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='adminuserauthpreference',
            index=models.Index(fields=['is_locked'], name='hoztech_adm_is_lock_33aa95_idx'),
        ),
        migrations.AddIndex(
            model_name='adminuserauthpreference',
            index=models.Index(fields=['last_login_attempt'], name='hoztech_adm_last_lo_cd4bef_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['cookie_name', 'timestamp'], name='hoztech_coo_cookie__a4f2c2_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['category', 'timestamp'], name='hoztech_coo_categor_5410cf_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['visitor', 'category'], name='hoztech_coo_visitor_467a14_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoraccess',
            index=models.Index(fields=['ip_address', 'timestamp'], name='hoztech_vis_ip_addr_4f5871_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoraccess',
            index=models.Index(fields=['session_id', 'timestamp'], name='hoztech_vis_session_cbc75d_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoraccess',
            index=models.Index(fields=['browser', 'os', 'device_type'], name='hoztech_vis_browser_991712_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoraccess',
            index=models.Index(fields=['country', 'city'], name='hoztech_vis_country_448157_idx'),
        ),
    ]
