# Generated by Django 5.2.1 on 2025-05-24 23:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoztech', '0008_alter_cookieconsent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminaccesslog',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Log de Acesso Administrativo', 'verbose_name_plural': 'Logs de Acesso Administrativo'},
        ),
        migrations.AlterModelOptions(
            name='adminauthimage',
            options={'ordering': ['category', 'name'], 'verbose_name': 'Imagem de Autenticação', 'verbose_name_plural': 'Imagens de Autenticação'},
        ),
        migrations.AlterModelOptions(
            name='adminuserauthpreference',
            options={'verbose_name': 'Preferência de Autenticação', 'verbose_name_plural': 'Preferências de Autenticação'},
        ),
        migrations.AlterModelOptions(
            name='dataexport',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Exportação de Dados', 'verbose_name_plural': 'Exportações de Dados'},
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='browser_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Configurações de privacidade do navegador'),
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='browser_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='consent_duration',
            field=models.IntegerField(blank=True, help_text='Duração do consentimento em dias', null=True),
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='consent_method',
            field=models.CharField(choices=[('click', 'Clique'), ('scroll', 'Scroll'), ('auto', 'Automático'), ('settings', 'Configurações')], default='click', max_length=50),
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='consent_source',
            field=models.CharField(choices=[('banner', 'Banner de Cookies'), ('settings', 'Configurações'), ('preferences', 'Preferências do Usuário'), ('auto', 'Automático')], default='banner', max_length=50),
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='data_retention',
            field=models.IntegerField(blank=True, help_text='Período de retenção em dias', null=True),
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='is_third_party',
            field=models.BooleanField(default=False, help_text='Cookie de terceiros'),
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='purpose',
            field=models.TextField(blank=True, help_text='Propósito do cookie', null=True),
        ),
        migrations.AddField(
            model_name='cookieconsent',
            name='third_party_domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='browser_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='conversion_type',
            field=models.CharField(blank=True, help_text='Tipo de conversão (download, contato, etc)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='device_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='is_bot',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='is_bounce',
            field=models.BooleanField(default=False, help_text='Visitante saiu sem interagir'),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='is_conversion',
            field=models.BooleanField(default=False, help_text='Visitante realizou uma conversão'),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='is_desktop',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='is_mobile',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='is_tablet',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='language',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='os_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='pages_visited',
            field=models.JSONField(blank=True, default=list, help_text='Lista de páginas visitadas em sequência'),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='referrer',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='referrer_domain',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='screen_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='screen_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='time_on_page',
            field=models.IntegerField(blank=True, help_text='Tempo em segundos', null=True),
        ),
        migrations.AddField(
            model_name='visitoraccess',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cookieconsent',
            name='category',
            field=models.CharField(choices=[('essential', 'Essencial'), ('performance', 'Desempenho'), ('marketing', 'Marketing'), ('analytics', 'Analytics'), ('preferences', 'Preferências'), ('security', 'Segurança')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pdfdownload',
            name='last_download',
            field=models.DateTimeField(blank=True, help_text='Data e hora do último download', null=True, verbose_name='Último download'),
        ),
        migrations.AddIndex(
            model_name='adminuserauthpreference',
            index=models.Index(fields=['require_password_change'], name='hoztech_adm_require_b3a0e9_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['is_third_party', 'third_party_domain'], name='hoztech_coo_is_thir_3ae7cc_idx'),
        ),
        migrations.AddIndex(
            model_name='cookieconsent',
            index=models.Index(fields=['consent_source', 'consent_method'], name='hoztech_coo_consent_9807cd_idx'),
        ),
        migrations.AddIndex(
            model_name='pdfdownload',
            index=models.Index(fields=['source'], name='hoztech_pdf_source_cb12aa_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoraccess',
            index=models.Index(fields=['is_mobile', 'is_tablet', 'is_desktop'], name='hoztech_vis_is_mobi_115392_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoraccess',
            index=models.Index(fields=['is_conversion', 'conversion_type'], name='hoztech_vis_is_conv_451097_idx'),
        ),
        migrations.AddIndex(
            model_name='visitoraccess',
            index=models.Index(fields=['referrer_domain'], name='hoztech_vis_referre_1e8fe6_idx'),
        ),
    ]
